### ISSUE TITLE
telegram to Minecraft messages 

### ISSUE THREAD

**Issue by PystoyPlayer** [alt-art/TelegramBridge#4]
Chat FROM telegram to Minecraft doesn't work. Messages from Minecraft TO telegram work
![Shot (2024-03-03 at 10 38PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/b6c0b840-473a-4726-8c3c-730d5aab8bed)

**Comment by alt-art** [comment]
This problem is already fixed, I just need to make a release I am sorry for this

**Comment by alt-art** [comment]
The new release have some features, you will need to update the config file

**Comment by PystoyPlayer** [comment]
np
Btw can you insert \n inside file %caption%, because when there's no caption an extra space appear
![IMAGE 2024-03-04 5:20:53 PM](https://github.com/alt-art/TelegramBridge/assets/88878911/d90c2113-eab8-4a92-8955-817e2fc1d281)

**Comment by alt-art** [comment]
Some users may want to do other type of formatting on caption and maybe this will break with a new line, but I will do that because I think this is fine for now.

About the media types is something that I have to think about because telegram does not have a generalized away to check if something is a media and I have to check every single value on the API. I personally don't know what telegram thinks what a GIF is, and to check these things is not so trivial.

What I can tell you is that every type of media in the config file has a value in the API that matches what the media is. But the last type is just a fallback type that is not used for now because I don't check for all media types, only the specified on the array.

The idea is that if I find something specific that I think would be media, I can simply add it to my condition, and this will make the type the fallback value.

**Comment by PystoyPlayer** [comment]
![Shot (2024-03-04 at 10 25PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/f18da64a-ea8c-4e6b-b0bb-72925f255c34)

**Comment by PystoyPlayer** [comment]
btw how about to make a pinned message with current stats ? Sth like that:
![Shot (2024-03-04 at 10 38PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/5e4af13a-9470-49f5-b506-373d1031bb92)

**Comment by alt-art** [comment]
Hmm, this is interesting. I think I could do this.

Can you explain to me how this works on the telegram side? I never used this plugin, nor did I know it was dead.

**Comment by alt-art** [comment]
> ![Shot (2024-03-04 at 10 25PM)@2x](https://private-user-images.githubusercontent.com/88878911/309876578-f18da64a-ea8c-4e6b-b0bb-72925f255c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODE1ODAsIm5iZiI6MTcwOTU4MTI4MCwicGF0aCI6Ii84ODg3ODkxMS8zMDk4NzY1NzgtZjE4ZGE2NGEtZWE4Yy00ZTZiLWIwYmItNzI5MjVmMjU1YzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE5NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjBjMGJlYTM1NzUwMDEzM2Y5MTAyY2U1ZTM2Zjc1NGVkZDM0ZmQ4ZWYzM2VkZmNiNzg4NGI4NTFjZDJhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxUu0W1MbetqpKIIjD2ZAwoJJ3wvq6KW-hMDOZQpLS0)

What did you send to give this error?

**Comment by PystoyPlayer** [comment]
> > ![Shot (2024-03-04 at 10 25PM)@2x](https://private-user-images.githubusercontent.com/88878911/309876578-f18da64a-ea8c-4e6b-b0bb-72925f255c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODE1ODAsIm5iZiI6MTcwOTU4MTI4MCwicGF0aCI6Ii84ODg3ODkxMS8zMDk4NzY1NzgtZjE4ZGE2NGEtZWE4Yy00ZTZiLWIwYmItNzI5MjVmMjU1YzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE5NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjBjMGJlYTM1NzUwMDEzM2Y5MTAyY2U1ZTM2Zjc1NGVkZDM0ZmQ4ZWYzM2VkZmNiNzg4NGI4NTFjZDJhNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxUu0W1MbetqpKIIjD2ZAwoJJ3wvq6KW-hMDOZQpLS0)
> 
> What did you send to give this error?

I suppose, that was after a user replied to a old message or a message that was sent while server was offline

**Comment by PystoyPlayer** [comment]
> Hmm, this is interesting. I think I could do this.
> 
> Can you explain to me how this works on the telegram side? I never used this plugin, nor did I know it was dead.

I think you can try to contact the dev, word "dead" is clickable

**Comment by alt-art** [comment]
> I suppose, that was after a user replied to a old message or a message that was sent while server was offline

Hmm, You replied with a media? Sticker o something? Because it is impossible, this value be null.

**Comment by alt-art** [comment]
> > Hmm, this is interesting. I think I could do this.
> > Can you explain to me how this works on the telegram side? I never used this plugin, nor did I know it was dead.
> 
> I think you can try to contact the dev, word "dead" is clickable

I have checked the source code of the plugin and I think I could do something even better

**Comment by PystoyPlayer** [comment]
> > I suppose, that was after a user replied to a old message or a message that was sent while server was offline
> 
> Hmm, You replied with a media? Sticker o something? Because it is impossible, this value be null.

idk sry, will try again later

**Comment by PystoyPlayer** [comment]
![Shot (2024-03-05 at 09 35PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/6a895d0e-fee4-4c2b-b208-a610bb2a2675)

**Comment by alt-art** [comment]
If this error appears again, please restart your server and send me the logs. This error is difficult to debug. This plugin is new and I'm still checking if there are any problems.

**Comment by PystoyPlayer** [comment]
> If this error appears again, please restart your server and send me the logs. This error is difficult to debug. This plugin is new and I'm still checking if there are any problems.

Sure. Also plugin disables (on restart) really slow
![Shot (2024-03-05 at 10 33PM)@2x](https://github.com/alt-art/TelegramBridge/assets/88878911/c1f7f803-3820-4974-abb3-6b5c5842177a)

**Comment by alt-art** [comment]
For me, it is the first to be disabled, maybe something with your sever? I have tested on spigot, but now my server is on paper.

**Comment by alt-art** [comment]
Keep in mind that the command `/reload` can cause problems, I have some code if the user uses `/restart` but the server community doesn't encourage you to use it.

**Comment by PystoyPlayer** [comment]
> Keep in mind that the command `/reload` can cause problems, I have some code if the user uses `/reload` but the server community doesn't encourage you to use it.

I don't, that was full restart
Current version: git-Purpur-2062 (MC: 1.20.1) - Latest

**Comment by PystoyPlayer** [comment]
idk what's the reason
```
[00:22:31 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:2961) ~[?:?]
        at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
[00:22:35 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:2961) ~[?:?]
        at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
[00:22:49 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:2961) ~[?:?]
        at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
        at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
[00:22:54 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:23:08 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:23:25 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:23:26 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:05 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:07 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:20 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:36 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:50 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:51 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:53 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:24:54 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:25:00 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:25:13 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:25:21 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:25:27 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
[00:25:58 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
java.lang.NullPointerException: null
```

**Comment by PystoyPlayer** [comment]
btw a suggestion: messages about server status ("Server started", "Server stopped" etc, like in DiscordSRV)

**Comment by alt-art** [comment]
I will add this as optional, because sometimes this can be annoying.

**Comment by alt-art** [comment]
> idk what's the reason
> 
> ```
> [00:22:31 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
> java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
>         at java.lang.String.replace(String.java:2961) ~[?:?]
>         at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
>         at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
>         at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
> [00:22:35 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
> java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
>         at java.lang.String.replace(String.java:2961) ~[?:?]
>         at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
>         at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
>         at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
> [00:22:49 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
> java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
>         at java.lang.String.replace(String.java:2961) ~[?:?]
>         at org.altart.telegrambridge.utils.Format.string(Format.java:13) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.TelegramBot.onMessage(TelegramBot.java:122) ~[TelegramBridge-1.1.0.jar:?]
>         at org.altart.telegrambridge.BotMessageHandler.onUpdateReceived(BotMessageHandler.java:52) ~[TelegramBridge-1.1.0.jar:?]
>         at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
>         at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBridge-1.1.0.jar:?]
>         at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[TelegramBridge-1.1.0.jar:?]
> [00:22:54 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:23:08 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:23:25 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:23:26 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:05 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:07 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:20 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:36 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:50 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:51 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:53 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:24:54 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:25:00 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:25:13 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:25:21 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:25:27 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> [00:25:58 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] null
> java.lang.NullPointerException: null
> ```

I will debug on pupur to see if something is different

**Comment by PystoyPlayer** [comment]
```
[23:57:08 ERROR]: [org.telegram.telegrambots.updatesreceivers.DefaultBotSession] api.telegram.org:443 failed to respond
org.apache.http.NoHttpResponseException: api.telegram.org:443 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.14.jar:4.4.14]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.14.jar:4.4.14]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.14.jar:4.4.14]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.14.jar:4.4.14]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.getUpdatesFromServer(DefaultBotSession.java:249) ~[TelegramBridge-1.1.0.jar:?]
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:188) ~[TelegramBridge-1.1.0.jar:?]
```
sending another error just to make you know
I suppose telegram servers were down that moment

**Comment by alt-art** [comment]
I made a test version of the pin feature that you can try to see if it works correctly.
